hold off;
% z_score_data = [CCLE_data_gbmlgg_zscore;CCLE_data_ov_zscore;TCGA_data_gbmlgg_zscore;TCGA_data_ov_zscore];
% [z_score_data_residual,z_score_data_pca_reconstructed] = pcares(z_score_data,2);
% z_score_data_pca_reconstructed = z_score_data_pca_reconstructed(:,1:2);
% CCLE_data_gbmlgg_zscore_pca = z_score_data_pca_reconstructed(1:size(CCLE_data_gbmlgg_zscore,1),:);
% step = size(CCLE_data_gbmlgg_zscore,1);
% CCLE_data_ov_zscore_pca = z_score_data_pca_reconstructed(step+1:step+size(CCLE_data_ov_zscore,1),:);
% step = step+size(CCLE_data_ov_zscore,1);
% TCGA_data_gbmlgg_zscore_pca = z_score_data_pca_reconstructed(step+1:step+size(TCGA_data_gbmlgg_zscore,1),:);
% step = step+size(TCGA_data_gbmlgg_zscore,1);
% TCGA_data_ov_zscore_pca = z_score_data_pca_reconstructed(step+1:step+size(TCGA_data_ov_zscore,1),:);
% scatter(CCLE_data_gbmlgg_zscore_pca(:,1),CCLE_data_gbmlgg_zscore_pca(:,2),[],'red');
% hold on;
% scatter(CCLE_data_ov_zscore_pca(:,1),CCLE_data_ov_zscore_pca(:,2),[],'blue');
% hold on;
% scatter(TCGA_data_gbmlgg_zscore_pca(:,1),TCGA_data_gbmlgg_zscore_pca(:,2),[],'green');
% hold on;
% scatter(TCGA_data_ov_zscore_pca(:,1),TCGA_data_ov_zscore_pca(:,2),[],'yellow');

% 
% raw_data = [CCLE_data_gbmlgg;CCLE_data_ov;TCGA_data_gbmlgg;TCGA_data_ov];
% [raw_data_residual,raw_data_pca_reconstructed] = pcares(raw_data,2);
% raw_data_pca_reconstructed = raw_data_pca_reconstructed(:,1:2);
% CCLE_data_gbmlgg_raw_pca = raw_data_pca_reconstructed(1:size(CCLE_data_gbmlgg,1),:);
% step = size(CCLE_data_gbmlgg,1);
% CCLE_data_ov_raw_pca = raw_data_pca_reconstructed(step+1:step+size(CCLE_data_ov,1),:);
% step = step+size(CCLE_data_ov,1);
% TCGA_data_gbmlgg_raw_pca = raw_data_pca_reconstructed(step+1:step+size(TCGA_data_gbmlgg,1),:);
% step = step+size(TCGA_data_gbmlgg,1);
% TCGA_data_ov_raw_pca = raw_data_pca_reconstructed(step+1:step+size(TCGA_data_ov,1),:);
% scatter(CCLE_data_gbmlgg_raw_pca(:,1),CCLE_data_gbmlgg_raw_pca(:,2),[],'red');
% hold on;
% scatter(CCLE_data_ov_raw_pca(:,1),CCLE_data_ov_raw_pca(:,2),[],'blue');
% hold on;
% scatter(TCGA_data_gbmlgg_raw_pca(:,1),TCGA_data_gbmlgg_raw_pca(:,2),[],'green');
% hold on;
% scatter(TCGA_data_ov_raw_pca(:,1),TCGA_data_ov_raw_pca(:,2),[],'yellow');
% 
% quantiled_data = [CCLE_data_gbmlgg_quantiled;CCLE_data_ov_quantiled;TCGA_data_gbmlgg_quantiled;TCGA_data_ov_quantiled];
% [quantiled_data_residual,quantiled_data_pca_reconstructed] = pcares(quantiled_data,2);
% quantiled_data_pca_reconstructed = quantiled_data_pca_reconstructed(:,1:2);
% CCLE_data_gbmlgg_quantiled_pca = quantiled_data_pca_reconstructed(1:size(CCLE_data_gbmlgg_quantiled,1),:);
% step = size(CCLE_data_gbmlgg_quantiled,1);
% CCLE_data_ov_quantiled_pca = quantiled_data_pca_reconstructed(step+1:step+size(CCLE_data_ov_quantiled,1),:);
% step = step+size(CCLE_data_ov_quantiled,1);
% TCGA_data_gbmlgg_quantiled_pca = quantiled_data_pca_reconstructed(step+1:step+size(TCGA_data_gbmlgg_quantiled,1),:);
% step = step+size(TCGA_data_gbmlgg_quantiled,1);
% TCGA_data_ov_quantiled_pca = quantiled_data_pca_reconstructed(step+1:step+size(TCGA_data_ov_quantiled,1),:);
% scatter(CCLE_data_gbmlgg_quantiled_pca(:,1),CCLE_data_gbmlgg_quantiled_pca(:,2),[],'red');
% hold on;
% scatter(CCLE_data_ov_quantiled_pca(:,1),CCLE_data_ov_quantiled_pca(:,2),[],'blue');
% hold on;
% scatter(TCGA_data_gbmlgg_quantiled_pca(:,1),TCGA_data_gbmlgg_quantiled_pca(:,2),[],'green');
% hold on;
% scatter(TCGA_data_ov_quantiled_pca(:,1),TCGA_data_ov_quantiled_pca(:,2),[],'yellow');

pair_quantiled_data = [CCLE_data_gbmlgg_pair_quantiled;CCLE_data_ov_pair_quantiled;TCGA_data_gbmlgg_pair_quantiled;TCGA_data_ov_pair_quantiled];
[pair_quantiled_data_residual,pair_quantiled_data_pca_reconstructed] = pcares(pair_quantiled_data,2);
pair_quantiled_data_pca_reconstructed = pair_quantiled_data_pca_reconstructed(:,1:2);
CCLE_data_gbmlgg_pair_quantiled_pca = pair_quantiled_data_pca_reconstructed(1:size(CCLE_data_gbmlgg_pair_quantiled,1),:);
step = size(CCLE_data_gbmlgg_pair_quantiled,1);
CCLE_data_ov_pair_quantiled_pca = pair_quantiled_data_pca_reconstructed(step+1:step+size(CCLE_data_ov_pair_quantiled,1),:);
step = step+size(CCLE_data_ov_pair_quantiled,1);
TCGA_data_gbmlgg_pair_quantiled_pca = pair_quantiled_data_pca_reconstructed(step+1:step+size(TCGA_data_gbmlgg_pair_quantiled,1),:);
step = step+size(TCGA_data_gbmlgg_pair_quantiled,1);
TCGA_data_ov_pair_quantiled_pca = pair_quantiled_data_pca_reconstructed(step+1:step+size(TCGA_data_ov_pair_quantiled,1),:);
scatter(CCLE_data_gbmlgg_pair_quantiled_pca(:,1),CCLE_data_gbmlgg_pair_quantiled_pca(:,2),[],'red');
hold on;
scatter(CCLE_data_ov_pair_quantiled_pca(:,1),CCLE_data_ov_pair_quantiled_pca(:,2),[],'blue');
hold on;
scatter(TCGA_data_gbmlgg_pair_quantiled_pca(:,1),TCGA_data_gbmlgg_pair_quantiled_pca(:,2),[],'green');
hold on;
scatter(TCGA_data_ov_pair_quantiled_pca(:,1),TCGA_data_ov_pair_quantiled_pca(:,2),[],'yellow');